services:
  api:
    build: api
    restart: unless-stopped
    init: true
    environment:
      PYTHON_ENV: development
      AZURE_AI_ACCESS_KEY: ${AZURE_AI_ACCESS_KEY}
      AZURE_AI_ENDPOINT: ${AZURE_AI_ENDPOINT}
    command:
      - >
        uv sync;
        exec uv run fastapi dev
        --host 0.0.0.0
        --port 8000
        --reload
        api/app.py;
    volumes:
      - ./api:/app
      - venv-data:/app/.venv
    ports:
      - '8000:8000'

  ui:
    image: oven/bun:1.1-alpine
    restart: unless-stopped
    init: true
    command:
      - /bin/sh
      - -eu
      - -c
      - bun install && exec bun run dev
    working_dir: /app
    volumes:
      - ./ui:/app
    ports:
      - '3000:3000'


volumes:
  venv-data:
