services:
  api:
    build: api
    restart: unless-stopped
    init: true
    env_file: api/.env
    command:
      - >
        poetry install --no-root;
        exec poetry run uvicorn
        --host 0.0.0.0
        --port 8000
        --reload
        --log-level debug
        --access-log
        api:app;
    volumes:
      - ./api:/app
      - venv-data:/app/.venv
    ports:
      - '8000:8000'

  ui:
    image: oven/bun:1.1-alpine
    restart: unless-stopped
    init: true
    command:
      - /bin/sh
      - -eu
      - -c
      - bun install && exec bun run dev
    working_dir: /app
    volumes:
      - ./ui:/app
    ports:
      - '3000:3000'


volumes:
  venv-data:
