services:
  ollama:
    image: ollama/ollama:0.4.3
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    volumes:
      - ${HOME}/.ollama:/root/.ollama
    ports:
      - '11434:11434'

  api:
    build: api
    restart: unless-stopped
    init: true
    env_file: api/.env
    command:
      - >
        poetry install --no-root;
        exec poetry run fastapi dev --host 0.0.0.0 --port 8000 --reload api/app.py;
    volumes:
      - ./api:/app
      - venv-data:/app/.venv
    ports:
      - '8000:8000'

volumes:
  venv-data:
