# fly.toml app configuration file generated for unreceiptify on 2024-11-29T13:59:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unreceiptify'
primary_region = 'sjc'
kill_timeout = 10

[build]
dockerfile = 'prod.Dockerfile'

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
