on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Notify build started
        uses: discord-actions/message@v2
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: >-
            **Build [#${{ gitea.run_number }}](${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }})**
            started for [${{ gitea.repository }}](${{ gitea.server_url }}/${{ gitea.repository }})
            by [${{ gitea.actor }}](${{ gitea.server_url }}/${{ gitea.actor }}).

      - name: Checkout code repo
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git.lab.kvd.studio
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            git.lab.kvd.studio/${{ gitea.repository }}:${{ gitea.sha }}
            git.lab.kvd.studio/${{ gitea.repository }}:latest
          file: prod.Dockerfile

      - name: Notify build success
        uses: discord-actions/message@v2
        if: success()
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: >-
            Build [#${{ gitea.run_number }}](${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }})
            for [${{ gitea.repository }}](${{ gitea.server_url }}/${{ gitea.repository }}) **succeeded**.

      - name: Notify build failure
        uses: discord-actions/message@v2
        if: ${{ always() && contains(needs.*.result, 'failure') }}
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          message: >-
            Build [#${{ gitea.run_number }}](${{ gitea.server_url }}/${{ gitea.repository }}/actions/runs/${{ gitea.run_number }})
            for [${{ gitea.repository }}](${{ gitea.server_url }}/${{ gitea.repository }}) **failed**.
